In [ ]:
import tensorflow as tf
import time
import input_data

In [ ]:
mnist = input_data.read_data_sets('mnist/', one_hot=True)

In [ ]:
def weight_variable(shape):
    initial = tf.truncated_normal(shape, stddev=0.1)
    return tf.Variable(initial)
def bias_variable(shape):
    initial = tf.constant(0.1,shape=shape)
    return tf.Variable(initial)

In [ ]:
def conv2d(x, W):
    return tf.nn.conv2d(x, W, strides=[1,1,1,1],padding='SAME')
def max_pool_2x2(x):
    return tf.nn.max_pool(x, ksize=[1,2,2,1], strides=[1,2,2,1], padding='SAME')

In [ ]:
start = time.clock()

## 第一层

In [ ]:
x = tf.placeholder(tf.float32,[None,784])
x_image = tf.reshape(x,[-1,28,28,1])
W_conv1 = weight_variable([5,5,1,32])
b_conv1 = bias_variable([32])

h_conv1 = tf.nn.relu(conv2d(x_image,W_conv1)+b_conv1)

h_pool1 = max_pool_2x2(h_conv1)

## 第二层

In [ ]:
W_conv2 = weight_variable([5,5,32,64])
b_conv2 = bias_variable([64])

h_conv2 = tf.nn.relu(conv2d(h_pool1,W_conv2) + b_conv2)

h_pool2 = max_pool_2x2(h_conv2)

## 第三层

In [ ]:
W_fc1 = weight_variable([7*7*64,1024])
b_fc1 = bias_variable([1024])

h_pool2_flat = tf.reshape(h_pool2, [-1,7*7*64])
h_fc1 = tf.nn.relu(tf.matmul(h_pool2_flat, W_fc1)+b_fc1)

keep_prob = tf.placeholder('float')
h_fc1_drop = tf.nn.dropout(h_fc1,keep_prob)

## 输出层

In [ ]:
W_fc2 = weight_variable([1024,10])
b_fc2 = bias_variable([10])

y_conv = tf.nn.softmax(tf.matmul(h_fc1_drop, W_fc2)+b_fc2)

In [ ]:
y_ = tf.placeholder('float',[None,10])
loss = -tf.reduce_sum(y_*tf.log(y_conv))
train_step = tf.train.AdamOptimizer(1e-4).minimize(loss)
correct_prediction = tf.equal(tf.argmax(y_conv,1),tf.argmax(y_,1))
accuracy = tf.reduce_mean(tf.cast(correct_prediction,'float'))

In [ ]:
sess = tf.Session()
sess.run(tf.initialize_all_variables())

In [ ]:
for i in range(5000):
    batch = mnist.train.next_batch(32)
    _,train_l,train_ac=sess.run([train_step,loss,accuracy],feed_dict={x:batch[0],y_:batch[1],keep_prob:0.5})
    print('loss:{0}\t--\taccuracy:{1}'.format(train_l,train_ac))
    if i%100 == 0:
        train_ac=sess.run([accuracy],feed_dict={x:mnist.test.images,y_:mnist.test.labels,keep_prob:1.0})
        print('test accuracy:{0}'.format(train_ac))

In [ ]:
end = time.clock()
print('running time is %g s'%(end-start))

In [33]:
oo = tf.placeholder('float',[None,10])
print(sess.run(oo,feed_dict={oo:[[2]*10]*9}))

[[2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2. 2. 2. 2. 2. 2.]]


In [30]:
import numpy as np
np.array(mnist.test.labels).shape

(10000, 10)

In [56]:
batch = mnist.train.next_batch(32)
uio,_,train_l,train_ac=sess.run([y_conv,train_step,loss,accuracy],feed_dict={x:batch[0],y_:batch[1],keep_prob:0.5})
print(uio)
print()


[[2.46729632e-03 1.62312621e-03 5.38653228e-04 3.30262105e-06
  2.60350276e-02 5.60750195e-05 9.67197359e-01 4.22194789e-05
  2.02544732e-03 1.14478316e-05]
 [5.71240037e-07 9.99800265e-01 1.85910303e-05 1.26279343e-08
  6.72112947e-05 5.09404927e-08 3.85147177e-05 7.08378502e-05
  3.38454515e-06 6.27992051e-07]
 [6.01866361e-08 1.28266209e-09 9.68617044e-08 6.08533057e-10
  9.99977946e-01 2.85854174e-10 2.35303332e-09 3.47322282e-09
  3.27859251e-09 2.18341811e-05]
 [9.75873081e-06 9.98811126e-01 7.37676237e-05 8.59670490e-06
  5.61414810e-04 7.07811614e-06 1.07638925e-05 3.65503773e-04
  1.34328337e-04 1.77634902e-05]
 [2.36277731e-09 6.69358144e-07 1.79417526e-07 9.99965668e-01
  5.02985875e-09 1.28569109e-05 1.96402605e-09 8.88170959e-08
  2.04834232e-05 4.80982756e-08]
 [8.21175126e-05 3.07169030e-05 2.08706991e-03 9.41686869e-01
  2.75297907e-06 4.87248339e-02 1.54329496e-06 6.04318362e-03
  1.21367724e-04 1.21939927e-03]
 [9.99805391e-01 3.24163716e-06 4.43112040e-05 7.46364393e

In [42]:
np.array(uio).shape

(32, 10)

In [44]:
print(tf.log(uio))

Tensor("Log_6:0", shape=(32, 10), dtype=float32)


In [46]:
a = sess.run(tf.log(uio))

In [47]:
np.array(a).shape

(32, 10)

In [48]:
uio

array([[6.74387479e-07, 3.30477348e-03, 5.24575531e-04, 1.06015286e-05,
        1.15521459e-06, 2.63558263e-07, 5.81850017e-08, 9.95709300e-01,
        3.18046747e-04, 1.30591259e-04],
       [1.59044117e-01, 2.45185947e-04, 7.07567632e-02, 6.45169690e-02,
        5.03595779e-03, 2.46725958e-02, 6.21635199e-01, 1.98476878e-03,
        3.95063423e-02, 1.26020433e-02],
       [1.45223339e-06, 9.94715989e-01, 3.81174497e-03, 2.29486741e-05,
        1.04799648e-04, 1.73979730e-04, 6.66605265e-05, 2.36869790e-04,
        8.60307482e-04, 5.27086604e-06],
       [9.99899387e-01, 7.70984943e-10, 9.01259778e-09, 1.58609459e-09,
        2.67652827e-11, 5.01332522e-07, 1.20999573e-06, 5.14131937e-09,
        7.18324955e-09, 9.89347755e-05],
       [1.23803780e-04, 4.70273299e-05, 1.80737392e-04, 3.38257050e-05,
        2.80768654e-06, 3.19358683e-03, 9.96242046e-01, 2.46374316e-06,
        1.72526488e-04, 1.24973292e-06],
       [9.99724925e-01, 5.75494710e-07, 2.69108859e-04, 1.06199725e-08,
   

In [49]:
a

array([[-1.42094612e+01, -5.71238756e+00, -7.55292130e+00,
        -1.14545126e+01, -1.36712246e+01, -1.51489916e+01,
        -1.66596375e+01, -4.29993169e-03, -8.05331230e+00,
        -8.94343853e+00],
       [-1.83857369e+00, -8.31349373e+00, -2.64850712e+00,
        -2.74082708e+00, -5.29115152e+00, -3.70206213e+00,
        -4.75401878e-01, -6.22225285e+00, -3.23129416e+00,
        -4.37389612e+00],
       [-1.34424076e+01, -5.29802125e-03, -5.56966829e+00,
        -1.06822500e+01, -9.16345978e+00, -8.65657139e+00,
        -9.61589718e+00, -8.34799957e+00, -7.05822086e+00,
        -1.21533155e+01],
       [-1.00617704e-04, -2.09833527e+01, -1.85246429e+01,
        -2.02619915e+01, -2.43439159e+01, -1.45059967e+01,
        -1.36248941e+01, -1.90859566e+01, -1.87515144e+01,
        -9.22104931e+00],
       [-8.99681282e+00, -9.96478176e+00, -8.61846542e+00,
        -1.02942896e+01, -1.27831497e+01, -5.74661064e+00,
        -3.76503239e-03, -1.29138288e+01, -8.66495991e+00,
        -1.

In [108]:
a = tf.constant(np.array([[0.1,1,1,1]]).astype('float16'))
b = tf.constant([[2,4],[5,6]])

In [110]:
-sess.run(tf.reduce_sum(a*tf.log(a)))

0.2302

In [114]:
a = tf.placeholder('float',[None,2])

In [116]:
sess.run(tf.reduce_sum(a*tf.log(a)),feed_dict={a:[[1,2],[2,3]]})

6.0684257